RestSupplyMVC/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestSupplyMVC.Controllers
{
    public class NavigationController : Controller
    {
        // GET: Navigation
        public ActionResult Index()
        {
            return View();
        }

    }
}

RestSupplyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RestSupply</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="control-label ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Navigation")" class="navbar-left"><img style="width: 60px;" src="https://drive.google.com/thumbnail?id=1qYDQ8hBkYlTlkSIfRZuln_7WhbrcOYBn"></a>
            </div>
        </div>
        <div class="container-fluid">
            <ul class="nav navbar-header navbar-nav">
                <li class="active">
                    <a href="@Url.Action("Index", "Navigation")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <div class="container body-content bottom">
        @RenderBody()
        <hr />
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/css")

    @RenderSection("scripts", required: false)
</body>
</html>