RestSupplyMVC/ViewModels/IngredientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using RestSupplyDB.Models.Ingredient;

namespace RestSupplyMVC.ViewModels
{
    public class IngredientViewModel
    {
        public int IngredientId { get; set; }

        [Display(Name = "Ingredient Name")]
        public string Name { get; set; }

        [Display(Name = "Ingredient Unit")]
        public string Unit { get; set; }

        public IEnumerable<SupplierViewModel> AllIngredientSuppliersList{ get; set; }
    }

    public class CreateIngredientViewModel : IngredientViewModel
    {
        public IEnumerable<SupplierViewModel> AllSuppliers { get; set; }
    }

    public class IngredientIndexViewModel
    {
        public CreateIngredientViewModel IngredientToCreate { get; set; }
        public IEnumerable<IngredientViewModel> IngredientsList { get; set; }
    }
}

RestSupplyMVC/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RestSupplyDB;
using RestSupplyDB.Models.Ingredient;
using RestSupplyDB.Models.Supplier;
using RestSupplyMVC.Helpers;
using RestSupplyMVC.Persistence;
using RestSupplyMVC.Repositories;
using RestSupplyMVC.ViewModels;

namespace RestSupplyMVC.Controllers
{
    public class IngredientsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public IngredientsController()
        {
            _unitOfWork = new UnitOfWork(new RestSupplyDbContext());
        }

        // GET: Ingredients
        [AuthorizeRoles]
        public ActionResult Index()
        {
            var dbIngredients = _unitOfWork.Ingredients.GetAll();
            var dbSuppliers = _unitOfWork.Suppliers.GetAll();

            var ingredientIndexVm = new IngredientIndexViewModel
            {
                IngredientToCreate = new CreateIngredientViewModel
                {
                    AllSuppliers = dbSuppliers.Select(i => new SupplierViewModel
                    {
                        Id = i.Id,
                        SupplierName = i.Name,
                        Address = i.Address,
                        Phone = i.Phone
                    })
                },
                IngredientsList = dbIngredients.Select(s => new IngredientViewModel
                {
                    IngredientId = s.Id,
                    Name = s.Name,
                    Unit = s.Unit,
                    
                    AllIngredientSuppliersList = s.SuppliersIngredients.Select(i => new SupplierViewModel
                    {
                        Id = i.Id
                    })
                })
            };
            return View(ingredientIndexVm);
        }

        // GET: Ingredients/Details/5
        [AuthorizeRoles]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ingredients ingredients = _unitOfWork.Ingredients.GetById(id.Value);
            if (ingredients == null)
            {
                return HttpNotFound();
            }

            var ingredientVm = new IngredientViewModel
            {
                IngredientId = ingredients.Id,
                Name = ingredients.Name,
                Unit = ingredients.Unit,
                AllIngredientSuppliersList = ingredients.SuppliersIngredients.Select(si => new SupplierViewModel
                {
                    Id = si.Id,
                    SupplierName = si.Supplier.Name,
                    Address = si.Supplier.Address,
                    Phone = si.Supplier.Phone
                })
            };
            return View(ingredientVm);
        }

        // GET: Ingredients/Edit/5
        [AuthorizeRoles]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredients dbIngredient = _unitOfWork.Ingredients.GetById(id.Value);

            var ingredientVm = new IngredientViewModel
            {
                IngredientId = dbIngredient.Id,
                Name = dbIngredient.Name,
                Unit = dbIngredient.Unit
            };
            return View(ingredientVm);
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles]
        public ActionResult Edit([Bind(Include = "IngredientId,Name,Unit")] IngredientViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var ingredient = _unitOfWork.Ingredients.GetById(vm.IngredientId);

            ingredient.Name = vm.Name;
            ingredient.Unit = vm.Unit;
            _unitOfWork.Complete();

            return View(vm);
        }

        // GET: Ingredients/Delete/5
        [AuthorizeRoles]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredients ingredients = _unitOfWork.Ingredients.GetById(id.Value);
            if (ingredients == null)
            {
                return HttpNotFound();
            }
            return View(ingredients);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles]
        public ActionResult DeleteConfirmed(int id)
        {
            Ingredients ingredients = _unitOfWork.Ingredients.GetById(id);
            _unitOfWork.Ingredients.Remove(ingredients);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult GetUnitByIngredientId(int id)
        {
            var response = _unitOfWork.Ingredients.GetById(id).Unit;
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [AuthorizeRoles]
        public ActionResult SaveIngredient(string ingredientName, string unit, SupplierViewModel[] suppliers)
        {
            string result = "Error! Saving ingredient Process Is Not Complete!";
            if (ingredientName != null && unit != null)
            {
                var ingredient = new Ingredients
                {
                    Name = ingredientName,
                    Unit = unit
                };

                if (suppliers != null && suppliers.Any())
                {
                    foreach (var supplier in suppliers)
                    {
                        ingredient.SuppliersIngredients.Add(
                            new SuppliersIngredients
                            {
                                SupplierId = supplier.Id,
                            });
                    }
                }

                _unitOfWork.Ingredients.Add(ingredient);
                _unitOfWork.Complete();
                result = "Success! Ingredient is saved!";
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                new RestSupplyDbContext().Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RestSupplyMVC/Controllers/SuppliersController.cs
using System.Collections.Generic;
using RestSupplyDB;
using RestSupplyDB.Models.Supplier;
using RestSupplyMVC.Persistence;
using RestSupplyMVC.ViewModels;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RestSupplyDB.Models.Ingredient;
using RestSupplyDB.Models.Menu;
using RestSupplyMVC.Helpers;

namespace RestSupplyMVC.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public SuppliersController()
        {
            _unitOfWork = new UnitOfWork(new RestSupplyDbContext());
        }

        // GET: Suppliers
        [AuthorizeRoles(Role.BranchManager, Role.KitchenManager)]
        public ActionResult Index()
        {
            var dbIngredients = _unitOfWork.Ingredients.GetAll();
            var dbSuppliers = _unitOfWork.Suppliers.GetAll();

            var supplierIndexVm = new SupplierIndexViewModel
            {
                CreateSupplierViewModel = new CreateSupplierViewModel
                {
                    AllIngredients = dbIngredients.Select(i => new IngredientViewModel
                    {
                        IngredientId = i.Id,
                        Name = i.Name,
                        Unit = i.Unit
                    }).ToList()
                },
                SuppliersList = dbSuppliers.Select(s => new SupplierViewModel
                {
                    Id = s.Id,
                    Address = s.Address,
                    SupplierName = s.Name,
                    Phone = s.Phone,
                    AllSupplierIngredientsList = s.SuppliersIngredients.Select(i => new IngredientViewModel
                    {
                        IngredientId = i.Id
                    }).ToList()
                })
            };
            return View(supplierIndexVm);
        }

        // GET: Suppliers/Details/5
        [AuthorizeRoles(Role.BranchManager, Role.KitchenManager)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var dbSupplier = _unitOfWork.Suppliers.GetById(id.Value);
            if (dbSupplier == null)
            {
                return HttpNotFound();
            }

            var currentUserId = User.Identity.GetUserId();
            // Get all supplier details and orders
            var supplierDetailsVm = new SupplierOrderViewModel
            {
                Address = dbSupplier.Address,
                Id = dbSupplier.Id,
                SupplierName = dbSupplier.Name,
                Phone = dbSupplier.Phone,

                // All ingredients that supplier supplies
                AllSupplierIngredientsList = dbSupplier.SuppliersIngredients.Select(si => new IngredientViewModel
                {
                    IngredientId = si.IngredientId,
                    Name = _unitOfWork.Ingredients.GetById(si.IngredientId).Name,
                    Unit = _unitOfWork.Ingredients.GetById(si.IngredientId).Unit
                }).ToList(),
                AllIngredients = _unitOfWork.Ingredients.GetAll().Select(i => new IngredientViewModel
                {
                    IngredientId = i.Id,
                    Name = i.Name,
                    Unit = i.Unit
                }).ToList(),
                UserKitchens = _unitOfWork.Kitchens.GetKitchensByUserId(currentUserId).Select(k => new KitchenViewModel
                {
                    KitchenId = k.Id,
                    KitchenAddress = k.Address,
                    KitchenName = k.Name
                }).ToList()
            };


            return View(supplierDetailsVm);
        }

        // GET: Suppliers/Edit/5
        [AuthorizeRoles]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = _unitOfWork.Suppliers.GetById(id.Value);
            if (supplier == null)
            {
                return HttpNotFound();
            }

            var supplierVm = new SupplierViewModel
            {
                Id = supplier.Id,
                Address = supplier.Address,
                SupplierName = supplier.Name,
                Phone = supplier.Phone
            };

            return View(supplierVm);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles]
        public ActionResult Edit(SupplierViewModel supplierVm)
        {
            if (ModelState.IsValid)
            {
                var dbSupplier = _unitOfWork.Suppliers.GetById(supplierVm.Id);

                dbSupplier.Address = supplierVm.Address;
                dbSupplier.Name = supplierVm.SupplierName;
                dbSupplier.Phone = supplierVm.Phone;
                
                _unitOfWork.Complete();

                return RedirectToAction("Details", new {id = dbSupplier.Id});
            }
            return View(supplierVm);
        }

        // GET: Suppliers/Delete/5
        [AuthorizeRoles]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var supplier = _unitOfWork.Suppliers.GetById(id.Value);
            if (supplier == null)
            {
                return HttpNotFound();
            }

            var supplierVm = new SupplierViewModel
            {
                Address = supplier.Address,
                Id = supplier.Id,
                SupplierName = supplier.Name,
                Phone = supplier.Phone,
                AllSupplierIngredientsList = supplier.SuppliersIngredients.Select(si => new IngredientViewModel
                {
                    IngredientId = si.IngredientId,
                    Name = _unitOfWork.Ingredients.GetById(si.IngredientId).Name,
                    Unit = _unitOfWork.Ingredients.GetById(si.IngredientId).Unit
                }).ToList()
            };
            
            return View(supplierVm);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeRoles]
        public ActionResult DeleteConfirmed(int id)
        {
            var context = new RestSupplyDbContext();
            Supplier supplier = context.SuppliersSet.Find(id);
            if (supplier != null)
            {
                var result = context.SuppliersSet.Remove(supplier);
                context.SaveChanges();
                //_unitOfWork.Complete();
            }    
        
        return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult AddSupplierIngredients(int supplierId,
            IngredientViewModel[] ingredients)
        {
            string result = "Error! Unable to add ingredients!";
            if (supplierId > 0 && ingredients.Any())
            {
                _unitOfWork.Suppliers.AddSupplierIngredients(supplierId,
                    ingredients.Select(i => i.IngredientId).ToList());
                _unitOfWork.Complete();

                 result = "Success! Ingredients were added!";
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AuthorizeRoles]
        public ActionResult RemoveIngredientFromSupplier(int ingredientId, int supplierId)
        {
            string result = "Error when removing ingredient from supplier!";
            if (ingredientId > 0 && supplierId > 0)
            {
                _unitOfWork.Suppliers.RemoveSupplierIngredient(supplierId, ingredientId);
                _unitOfWork.Complete();
                result = "Success";
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AuthorizeRoles]
        public ActionResult SaveSupplier(string supplierName, string supplierAddress, string supplierPhone,
            IngredientViewModel[] ingredients)
        {
            string result = "Error! Saving supplier process Is Not Complete!";
            if (supplierName != null && ingredients != null)
            {
                var supplier = new Supplier
                {
                    Name = supplierName,
                    Address = supplierAddress,
                    Phone = supplierPhone
                };
                foreach (var ingredientItem in ingredients)
                {
                    supplier.SuppliersIngredients.Add(
                        new SuppliersIngredients
                        {
                            IngredientId = ingredientItem.IngredientId
                        });
                }


                _unitOfWork.Suppliers.Add(supplier);
                _unitOfWork.Complete();

                result = "Success! Supplier is saved!";
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                new RestSupplyDbContext().Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RestSupplyMVC/Views/Ingredients/Delete.cshtml
@model RestSupplyDB.Models.Ingredient.Ingredients

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredients</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RestSupplyMVC/Views/Ingredients/Details.cshtml
@model RestSupplyMVC.ViewModels.IngredientViewModel

@{
    ViewBag.Title = "Ingredient Details";
}

<h2>Ingredient Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dd>
            <div class="panel-body">
                <table class="table table-striped table-responsive">
                    <tbody>
                        <tr>
                            <td><b>Ingredient Name:</b> @Model.Name</ td >
                            <td><b>Ingredient Unit:</b> @Model.Unit </ td >
                            <td> @Html.ActionLink("Edit Basic Info", "Edit", new { id = Model.IngredientId })</ td >

                        </tr>
                    <tr>
                        <td colspan="3">
                            <table class="table table-bordered">
                                <tbody>
                                @if (Model.AllIngredientSuppliersList == null || !Model.AllIngredientSuppliersList.Any())
                                {
                                    <h3>No Suppliers Currently supply this Ingredients!</h3>
                                }
                                else
                                {
                                    <tr>
                                        <th>Supplier Name</th>
                                        <th>Supplier Address</th>
                                        <th>Supplier Contact Phone</th>


                                    </tr>

                                    foreach (var ingredient in Model.AllIngredientSuppliersList)
                                     {
                                         <tr>
                                             <td>@ingredient.SupplierName</td>
                                             <td>@ingredient.Address</td>
                                             <td>@ingredient.Phone</td>
                                         </tr>
                                     }
                                }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Assign Ingredient to Supplier here", "Index","Suppliers", null,null) 

</p>

RestSupplyMVC/Views/Ingredients/Edit.cshtml
@model RestSupplyMVC.ViewModels.IngredientViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingredients</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IngredientId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestSupplyMVC/Views/Ingredients/Index.cshtml
@model RestSupplyMVC.ViewModels.IngredientIndexViewModel

@{
    ViewBag.Title = "Ingredients";
}

<h2>All Ingredients</h2>

<p align="right">
    <button style="margin-right:10px" class="btn btn-primary " onclick="addNewOrder()">Add A New Ingredient</button>

</p>
<table class="table">
    <tr>

    </tr>
    @if (Model.IngredientsList.Count() != 0)
    {
        foreach (var item in Model.IngredientsList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Details and Actions", "Details", new { id = item.IngredientId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IngredientId })
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td>
                <div class="panel-body">
                    <h3 style="color:red;">No Ingredients!</h3>
                </div>
            </td>
        </tr>
    }


</table>

<div class="modal fade" id="newOrderModal">
    <div class="modal-dialog modal-lg" style=" width: 900px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h4>Add New Ingredient</h4>
            </div>
            <form id="NewOrderForm">
                <div class="modal-body">
                    @*Customer Details*@
                    <h5 style="color:#112247"> Ingredient</h5>
                    <hr />
                    <div class="form-horizontal">
                        <input type="hidden" id="Id" />
                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Ingredient Name
                            </label>
                            <div class="col-md-4">
                                <input type="text" id="ingredient" name="ingredient" placeholder="insert name" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Unit 
                            </label>
                            <div class="col-md-4">
                                <input type="text" id="unit" name="unit" placeholder="gram, kilo etc." class="form-control" />
                            </div>
                        </div>
                    </div>

                    @*Order Details*@
                    <h5 style="margin-top:10px;color:#112247">Choose Suppliers</h5>
                    <hr />
                    <div class="form-horizontal">
                        <input type="hidden" id="IngredientId" />
                        <div class="form-group">
                            <label class="control-label col-md-2">
                                Add New
                            </label>
                            <div class="col-md-4">
                                @Html.DropDownListFor(model => model.IngredientToCreate.AllSuppliers, new SelectList(Model.IngredientToCreate.AllSuppliers, "Id", "SupplierName"), "", new { @id = "name", @class = "form-control" })
                            </div>
                        </div>
                            
                        <div class="form-group">
                            <div class="col-md-1 col-lg-offset-1">
                                <a id="addToList" class="btn btn-primary">Add To List</a>
                            </div>
                        </div>
                        <table id="detailsTable" class="table">
                            <thead>
                                <tr>
                                    <th style="width:5%"></th> @*hidden SupplierId column*@
                                    <th style="width: 85%"> Supplier Name</th>
                                    <th style="width: 10%"></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button id="saveIngredient" type="submit" class="btn btn-danger">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts{
    <script>
        //Show Modal.
        function addNewOrder() {
            $("#newOrderModal").modal();
            // Hiding the SupplierId column
            $('table#detailsTable td:nth-child(1),table#detailsTable th:nth-child(1)').hide();
        }
        //Add Multiple Order.
        $("#addToList").click(function (e) {
            e.preventDefault();

            if ($.trim($("#name").val()) == "") return;

            var id = $("#name option:selected").val(),
                name = $("#name option:selected").text(),
                detailsTableBody = $("#detailsTable tbody");

            var productItem = '<tr><td>' + id + '</td><td>' + name + '</td><td><a data-itemId="0" href="#" class="deleteItem">Remove</a></td></tr>';
            detailsTableBody.append(productItem);

            // Hiding the SupplierId column
            $('table#detailsTable td:nth-child(1),table#detailsTable th:nth-child(1)').hide();

            clearItem();

        });
        //After Add A New Ingredient In The List, Clear Clean The Form For Add More Order.
        function clearItem() {
            $("#name option:selected").remove();
        }
        // After Add A New Ingredient In The List, If You Want, You Can Remove It.
        $(document).on('click', 'a.deleteItem', function (e) {
            e.preventDefault();
            var $self = $(this);
            if ($(this).attr('data-itemId') == "0") {
                $(this).parents('tr').css("background-color", "#ff6347").fadeOut(800, function () {
                    $(this).remove();
                });
            }
        });
        //After Click Save Button Pass All Data View To Controller For Save Database
        function saveIngredient(data) {
            return $.ajax({
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                type: 'POST',
                url: "/Ingredients/SaveIngredient",
                data: data,
                success: function (result) {
                    alert(result);
                    location.reload();
                },
                error: function () {
                    alert("Error!");
                }
            });
        }
        //Collect Multiple Order List For Pass To Controller
        $("#saveIngredient").click(function (e) {
            e.preventDefault();

            var ingredientsArr = [];
            ingredientsArr.length = 0;

            $.each($("#detailsTable tbody tr"), function () {
                ingredientsArr.push({
                    id: $(this).find('td:eq(0)').html()
                });
            });


            var data = JSON.stringify({
                ingredientName: $("#ingredient").val(),
                unit: $("#unit").val(),
                suppliers: ingredientsArr
            });

            $.when(saveIngredient(data)).then(function (response) {
                console.log(response);
            }).fail(function (err) {
                console.log(err);
            });
        });
    </script>
}