RestSupplyMVC/Controllers/UserDashboardController.cs
using Microsoft.AspNet.Identity;
using RestSupplyDB;
using RestSupplyDB.Models.AppUser;
using RestSupplyMVC.Persistence;
using RestSupplyMVC.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using RestSupplyMVC.Helpers;

namespace RestSupplyMVC.Controllers
{
    public class UserDashboardController : Controller
    {
        private readonly RestSupplyDbContext _dbContext;
        private readonly IUnitOfWork _unitOfWork;

        public UserDashboardController()
        {
            _dbContext = new RestSupplyDbContext();
            _unitOfWork = new UnitOfWork(_dbContext);
        }

        [AuthorizeRoles]
        public ActionResult Edit(string id)
        {
            // Get all roles from the database
            var user = _unitOfWork.Users.GetById(id);
            UserViewModel model = new UserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                PrivateName = user.FirstName,
                LastName = user.LastName,
                UserRolesList = _unitOfWork.Roles.GetRolesByUserId(user.Id).Select(r => new RoleViewModel
                {
                    RoleId = r.RoleId,
                    RoleName = _unitOfWork.Roles.GetById(r.RoleId).Name
                }).ToList(),
                AllRolesList = _unitOfWork.Roles.GetAll().Select(r => new RoleViewModel
                {
                    RoleId = r.Id,
                    RoleName = r.Name
                }).ToList()
            };



            return View(model);
        }

        // POST: Update the user data
        [HttpPost]
        [AuthorizeRoles]
        public ActionResult Edit(UserViewModel vm)
        {
            if (!ModelState.IsValid || string.IsNullOrEmpty(vm.Id))
            {
                return RedirectToAction("Index");
            }
            var userToUpdate = _unitOfWork.Users.GetById(vm.Id);
            userToUpdate.FirstName = vm.PrivateName;
            userToUpdate.LastName = vm.LastName;


            foreach (var roleName in vm.UpdatedUserRoleNamesArr)
            {
                _unitOfWork.Users.AddRoleToUser(userToUpdate.Id, roleName);
            }
            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }


        [AuthorizeRoles]
        public ActionResult Index()
        {
            var users = _unitOfWork.Users.GetAll().ToList();
            var usersListViewModel = new UsersListViewModel
            {
                UsersList = new List<UserViewModel>()

            };

            foreach (var user in users)
            {
                var userRolesVm = user.Roles.ToList().Select(r => new RoleViewModel
                {
                    RoleId = r.RoleId,
                    RoleName = _unitOfWork.Roles.GetById(r.RoleId).Name
                }).ToList();
                usersListViewModel.UsersList.Add(new UserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    PrivateName = user.FirstName,
                    LastName = user.LastName,
                    UserRolesList = userRolesVm
                });
            }
            return View(usersListViewModel);
        }


        [HttpPost]
        [AuthorizeRoles]
        [ActionName("SearchUsers")]
        public async Task<ActionResult> SearchUsers(UserViewModel model)
        {
            AppUser user = null;

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(model.Email))
                {
                    // Create a user manager
                    var userManager = new AppUserManager(new AppUserStore(_dbContext));
                    user = await userManager.FindByEmailAsync(model.Email);
                }

                if (user != null)
                {
                    var dbRoles = _unitOfWork.Roles.GetAll();
                    var userRoles = user.Roles.ToList();

                    List<RoleViewModel> userRolesViewModel =
                        userRoles.Select(x => new RoleViewModel()
                        {
                            RoleId = x.RoleId,
                            RoleName = dbRoles.FirstOrDefault(s => s.Id == x.RoleId).Name
                        }).ToList();

                    List<RoleViewModel> allRolesViewModel = dbRoles.Select(x => new RoleViewModel()
                    {
                        RoleId = x.Id,
                        RoleName = x.Name
                    }).ToList();



                    var userVm = new UserViewModel
                    {
                        Id = user.Id,
                        Email = user.Email,
                        PrivateName = user.FirstName,
                        LastName = user.LastName,
                        AllRolesList = allRolesViewModel,
                        UserRolesList = userRolesViewModel
                    };
                    return View("Edit", userVm);
                }
            }


            return RedirectToAction("Admin");
        }

        // GET: UserDashboard
        [Authorize(Roles = "Admin")]
        [AuthorizeRoles]
        public ActionResult Admin(string id)
        {
            UserViewModel model = new UserViewModel
            {
                Id = id
            };

            return View(model);
        }
    }
}

RestSupplyMVC/Views/UserDashboard/Admin.cshtml
@model RestSupplyMVC.ViewModels.UserViewModel

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    User Dashboard
</h2>


<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                    Users
                </a>
            </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse in">
            <div class="panel-body" id="usersListContent">
                @{
                    // Check if a user was posted to this view, if so display the user modal edit
                    if(!string.IsNullOrEmpty(Model.Id))
                    {
                        @Html.Action("Edit", "UserDashboard", new { id = Model.Id })
                    }
                }
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <div class="col-md-10">
                            <p>Search a user by an email address</p>
                            @Html.LabelFor(m => m.Email)
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <h3></h3>
                            <button type="submit" class="btn btn-primary" formaction='@Url.Action("SearchUsers", "UserDashboard")'>Search</button>
                        </div>
                    </div>
                    <p>
                        @Html.ActionLink("Show all registered users", "Index")
                    </p>
                        }
                    </div>
                </div>
  
</div>
</div>

RestSupplyMVC/Views/UserDashboard/Edit.cshtml
@model RestSupplyMVC.ViewModels.UserViewModel

@using (Html.BeginForm())
{
  
    <h2>Edit User</h2>
    <body>
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.HiddenFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PrivateName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrivateName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrivateName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.AllRolesList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-sm-4">
                    @Html.ListBoxFor(model => model.UpdatedUserRoleNamesArr, new MultiSelectList(Model.AllRolesList, "RoleName", "RoleName",Model.CurrentUserRoleNamesArr), new { multiple = "true", id = "dropDown" })

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button formaction="@Url.Action("Edit", "UserDashboard")" id="save-user-edit" type="submit" class="btn btn-default" name="UpdateUserProfile" value="UpdateUserProfile">Save Changes</button>
                </div>
            </div>
        </div>

    </body>
}

RestSupplyMVC/Views/UserDashboard/Index.cshtml
@model RestSupplyMVC.ViewModels.UsersListViewModel



@*<div class="modal fade modal-user-list" id="display-user-modal">
    <div class="modal-dialog modal-lg" style=" width: 900px !important;">*@
@*<div class="modal-content">*@
@*<div class="modal-header">*@
@*<a href="#" class="close" data-dismiss="modal">&times;</a>*@
<h2>System Users</h2>
@*</div>*@
@*<div class="modal-body">*@
<table class="table" width="100">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Roles</th>

        <th scope="col">Actions</th>
    </tr>
    <tbody>
        @if (Model.UsersList.Any())
        {
            int count = 1;
            foreach (var item in Model.UsersList)
            {
                <tr>
                    <th scope="row">@count</th>
                    @{ count = count + 1;}
                    <td> @Html.DisplayFor(modelItem => item.Email) </td>
                    <td> @Html.DisplayFor(modelItem => item.PrivateName) </td>
                    <td> @Html.DisplayFor(modelItem => item.LastName) </td>
                    <td>@Html.DisplayFor(modelItem => item.UserRolesAsString) </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", "UserDashboard", new { id = item.Id }, new { @id = "display-user-link" })
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    <div class="panel-body">
                        <h3 style="color:red;">No users were found</h3>
                    </div>
                </td>
            </tr>

        }
    </tbody>
</table>
@*</div>*@

@*</div>*@
@*</div>
    </div>*@
@*@section scripts
    {
        <script>
            // Show the modal
            $("#display-user-modal").modal('show');
        </script>
    }*@

RestSupplyMVC/Views/UserDashboard/_SystemUsersList.cshtml
@model RestSupplyMVC.ViewModels.UsersListViewModel



@*<div class="modal fade modal-user-list" id="display-user-modal">
    <div class="modal-dialog modal-lg" style=" width: 900px !important;">*@
@*<div class="modal-content">*@
@*<div class="modal-header">*@
@*<a href="#" class="close" data-dismiss="modal">&times;</a>*@
<h2>Edit User</h2>
@*</div>*@
@*<div class="modal-body">*@
<table class="table" width="100">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Roles</th>

        <th scope="col">EDIT</th>
    </tr>
    <tbody>
        @if (Model.UsersList.Any())
        {
            int count = 1;
            foreach (var item in Model.UsersList)
            {
                <tr>
                    <th scope="row">@count</th>
                    @{ count = count + 1;}
                    <td> @Html.DisplayFor(modelItem => item.Email) </td>
                    <td> @Html.DisplayFor(modelItem => item.PrivateName) </td>
                    <td> @Html.DisplayFor(modelItem => item.LastName) </td>
                    <td> @String.Join(", ", item.UserRolesList.Select(r => r.RoleName)) </td>

                    <td>
                        @Html.ActionLink("display-edit-user-link", "_SystemUserEdit", "UserDashboard", new { id = item.Id }, new { @id = "display-user-link" })
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    <div class="panel-body">
                        <h3 style="color:red;">No users were found</h3>
                    </div>
                </td>
            </tr>

        }
    </tbody>
</table>
@*</div>*@

@*</div>*@
@*</div>
    </div>*@
@*@section scripts
    {
        <script>
            // Show the modal
            $("#display-user-modal").modal('show');
        </script>
    }*@